### ISSUE TITLE
How to Use and Get Token to access API ?

### ISSUE THREAD

**Issue by asepwaee** [aribrilliantsyah/novel-scrapper#1]

**Comment by aribrilliantsyah** [comment]
Thank you to open a new issue
This repo is for education purposes only and cannot use for commercial

Step configuration 
1. cp .env.example .env (create new .env file)
2. Add `TOKEN_KEY=secret_token` (you can generate use anything generator)
3. Install adonis-cli `npm i -g @adonisjs/cli` 
4. Next `npm install` inside repo dir
5. You can check all route use `adonis route:list`
6. Finally `adonis serve` for start services
7. Set header `Authorization: Bearer secret_token (env)` 

Sample usage:
![image](https://user-images.githubusercontent.com/29217948/168324421-23c96452-2254-4a03-a64e-a250b20e0f76.png)

![image](https://user-images.githubusercontent.com/29217948/168325037-7372c4ff-ba2b-475a-b656-fbe72fd5dd83.png)

![image](https://user-images.githubusercontent.com/29217948/168324497-a6e139a6-8850-4f46-9fa5-f9ba1bd35787.png)

**Comment by asepwaee** [comment]
ok thanks for the information. very help full
